SELECT * FROM TAB;
-- 정임 : TAXFREE, CART, ORDERS, ORDER_DETAIL


-- (1) TAXFREE TABLE
SELECT * FROM TAXFREE;
DROP TABLE TAXFREE;
DROP SEQUENCE PRODUCT_SEQ;

CREATE SEQUENCE PRODUCT_SEQ MAXVALUE 9999999999 NOCYCLE NOCACHE;
CREATE TABLE TAXFREE (
    PNUM    NUMBER(10)   PRIMARY KEY, -- 상품 번호(시퀀스)
    PNAME   VARCHAR2(50) NOT NULL,    -- 상품 이름
    PPRICE  NUMBER(10)   NOT NULL,    -- 상품 가격
    PIMAGE1 VARCHAR2(50),             -- 상품 메인 이미지
    PIMAGE2 VARCHAR2(50),             -- 상품 이미지2
    PIMAGE3 VARCHAR2(50),             -- 상품 이미지3
    PSTOCK  NUMBER(10)   NOT NULL,    -- 상품 재고
    PLOC    VARCHAR2(50) NOT NULL     -- 상품의 현재 위치(도시)
);

-- DUMMY
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC)
    VALUES(PRODUCT_SEQ.NEXTVAL, '샤넬립스틱', 30, NULL, NULL, NULL, 30, 'PARIS');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC)
    VALUES(PRODUCT_SEQ.NEXTVAL, '맥소바', 33, NULL, NULL, NULL, 120, 'LONDON');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC)
    VALUES(PRODUCT_SEQ.NEXTVAL, '디올향수', 180, NULL, NULL, NULL, 100, 'TOKYO');

-- (2) CART TABLE
DROP TABLE CART;
DROP SEQUENCE CART_SEQ;

CREATE SEQUENCE CART_SEQ MAXVALUE 9999999999 NOCYCLE NOCACHE;
CREATE TABLE CART(
    CARTNUM NUMBER(10)   PRIMARY KEY,                  -- 장바구니번호(시퀀스)
    PNUM    NUMBER(10)   NOT NULL REFERENCES TAXFREE,  -- 상품 번호
    MID     VARCHAR2(50) NOT NULL REFERENCES CUSTOMER, -- 회원 아이디
    COST    NUMBER(10)   NOT NULL,                     -- 가격
    QTY     NUMBER(10)   NOT NULL                      -- 수량
);

-- DUMMY
INSERT INTO CART (CARTNUM, PNUM, MID, COST, QTY)
    VALUES(CART_SEQ.NEXTVAL, 1, 'aaa', 3*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 1), 3);
INSERT INTO CART (CARTNUM, PNUM, MID, COST, QTY)
    VALUES(CART_SEQ.NEXTVAL, 1, 'bbb', 2*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 1), 2);
INSERT INTO CART (CARTNUM, PNUM, MID, COST, QTY)
    VALUES(CART_SEQ.NEXTVAL, 2, 'aaa', 3*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 2), 3);


-- (3) ORDERS TABLE 
DROP TABLE ORDERS;
DROP SEQUENCE ORDER_SEQ;

CREATE SEQUENCE ORDER_SEQ MAXVALUE 9999999999 NOCYCLE NOCACHE;
CREATE TABLE ORDERS (
    OR_NUM NUMBER(10)   PRIMARY KEY,                  -- 주문 번호(시퀀스)
    MID    VARCHAR2(50) NOT NULL REFERENCES CUSTOMER, -- 회원 아이디
    ORDATE DATE DEFAULT SYSDATE NOT NULL              -- 주문 날짜
);

-- DUMMY
INSERT INTO ORDERS 
    VALUES (TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.NEXTVAL, '0000')), 
            'aaa', TO_DATE('2022-07-24', 'YYYY-MM-DD'));
INSERT INTO ORDERS 
    VALUES (TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.NEXTVAL, '0000')), 
            'ccc', SYSDATE);
INSERT INTO ORDERS 
    VALUES (TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.NEXTVAL, '0000')), 
            'aaa', TO_DATE('2022-07-29', 'YYYY-MM-DD'));
INSERT INTO ORDERS 
    VALUES (TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.NEXTVAL, '0000')), 
            'ddd', SYSDATE);
INSERT INTO ORDERS 
    VALUES (TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.NEXTVAL, '0000')), 
            'aaa', TO_DATE('2022-07-25', 'YYYY-MM-DD'));
INSERT INTO ORDERS 
    VALUES (TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.NEXTVAL, '0000')), 
            'bbb', TO_DATE('2022-07-21', 'YYYY-MM-DD'));
INSERT INTO ORDERS 
    VALUES (TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.NEXTVAL, '0000')), 
            'bbb', TO_DATE('2022-07-24', 'YYYY-MM-DD'));

-- (4) ORDER_DETAIL
DROP TABLE ORDER_DETAIL;
DROP SEQUENCE ORDERDETAIL_SEQ;

CREATE SEQUENCE ORDERDETAIL_SEQ MAXVALUE 9999999999 NOCYCLE NOCACHE;
CREATE TABLE ORDER_DETAIL(
    ORD_NUM    NUMBER(10) PRIMARY KEY,                   -- 주문 완료 번호
    OR_NUM     NUMBER(10) NOT NULL REFERENCES ORDERS,    -- 주문 번호
    PNUM       NUMBER(10) NOT NULL REFERENCES TAXFREE,   -- 상품 번호
    COST       NUMBER(10) NOT NULL,                      -- 총 상품 가격
    QTY        NUMBER(10) NOT NULL                       -- 수량
);

-- DUMMY
-- 주문1
INSERT INTO ORDER_DETAIL (ORD_NUM, OR_NUM, PNUM, COST, QTY)
    VALUES(ORDERDETAIL_SEQ.NEXTVAL, 2207290001, 1, 3*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 1), 3);
UPDATE TAXFREE SET PSTOCK = PSTOCK-3 WHERE PNUM = 1; -- 재고 수정
-- 주문2
INSERT INTO ORDER_DETAIL (ORD_NUM, OR_NUM, PNUM, COST, QTY)
    VALUES(ORDERDETAIL_SEQ.NEXTVAL, 2207290002, 2, 1*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 2), 1);
UPDATE TAXFREE SET PSTOCK = PSTOCK-1 WHERE PNUM = 2; -- 재고 수정
-- 주문3
INSERT INTO ORDER_DETAIL (ORD_NUM, OR_NUM, PNUM, COST, QTY)
    VALUES(ORDERDETAIL_SEQ.NEXTVAL, 2207290006, 3, 1*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 3), 1);
UPDATE TAXFREE SET PSTOCK = PSTOCK-1 WHERE PNUM = 3; -- 재고 수정

COMMIT;


-- SQL / 면세 taxfree
SELECT * FROM TAXFREE;
-- 1. insertProduct 상품등록
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC)
    VALUES(PRODUCT_SEQ.NEXTVAL, '초콜릿', 10, NULL, NULL, NULL, 32, 'OASAKA');
-- 2. modifyProduct 상품수정
UPDATE TAXFREE SET PPRICE = 12,
                   PIMAGE1 = NULL,
                   PIMAGE2 = NULL,
                   PIMAGE3 = NULL,
                   PSTOCK = 160,
                   PLOC   = 'LONDON'
                WHERE PNUM = 4;
-- 3. deleteProduct 상품삭제
DELETE FROM TAXFREE WHERE PNUM = 4;
-- 4. countProduct 상품개수 / 페이징을 위한
SELECT COUNT(*) FROM TAXFREE;
-- 5. listProduct 상품리스트 - paging
SELECT * FROM TAXFREE ORDER BY PNUM DESC; -- 서브쿼리
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM TAXFREE ORDER BY PNUM DESC)A) WHERE RN BETWEEN 1 AND 2;
-- 6. detailProduct 상품상세보기 - pnum
SELECT * FROM TAXFREE WHERE PNUM = 1;
-- 7. 검색 searchProduct
SELECT * FROM TAXFREE WHERE PNAME LIKE '%'||'샤'||'%';


-- SQL / 장바구니 CART
-- 1. insertCart 장바구니 추가
-- 상품번호를 받아와서 장바구니 번호랑 회원 아이디, 총 가격, 수량 저장
INSERT INTO CART (CARTNUM, PNUM, MID, COST, QTY)
    VALUES(CART_SEQ.NEXTVAL, 2, 'aaa', 3*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 2), 3);
-- 2. deleteCart 장바구니 삭제
DELETE FROM CART WHERE MID = 'aaa';
-- 3. listCart 장바구니 리스트
SELECT * FROM CART C, TAXFREE T WHERE C.PNUM = T.PNUM AND MID = 'aaa' ;

-- 4. 장바구니 총 수량
SELECT COUNT(*) FROM CART WHERE MID='aaa';


-- SQL / 주문테이블 ORDERS
-- 1. insertOrderDetail 주문 
INSERT INTO ORDER_DETAIL (ORD_NUM, OR_NUM, PNUM, COST, QTY)
    VALUES(ORDERDETAIL_SEQ.NEXTVAL, 2207280001, 1, 3*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 1), 3);
-- 1-1. 주문 후 재고 수정 remainProduct
UPDATE TAXFREE SET PSTOCK = PSTOCK-3 WHERE PNUM = 1; -- 재고 수정 / 주문이 완료된 후에 재고 수정하는 함수
-- 2. insertOrders 오더테이블 장바구니에 담아주고
INSERT INTO ORDERS 
    VALUES (TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.NEXTVAL, '0000')), 
            'aaa', TO_DATE('2022-07-25', 'YYYY-MM-DD'));
-- 3. insertOrderDetail 주문 상세 내역에 장바구니 데이터 넣기
INSERT INTO ORDER_DETAIL (ORD_NUM, OR_NUM, PNUM, COST, QTY)
    VALUES(ORDERDETAIL_SEQ.NEXTVAL, 2207280001, 1, 3*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 1), 3);
SELECT * FROM CART WHERE MID='aaa'; -- 내역이 들어가 있는지 확인하고
select * from order_detail;
-- 4. orderdetail 결제정보
insert into order_Detail
    select orderdetail_seq.nextval,  TO_CHAR(SYSDATE, 'YYMMDD') || TRIM(TO_CHAR(ORDER_SEQ.currVAL, '0000')), pnum, cost, qty from cart where mid='aaa' ;
-- deleteCart 장바구니에 담겨진 물품 삭제
delete cart where mid='aaa';

commit;
