SELECT * FROM TAB;
-- TAXFREE, CART, ORDERS, ORDER_DETAIL
SELECT * FROM TAXFREE;
SELECT * FROM CART;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAIL;

DROP TABLE TAXFREE CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;

-- (1) TAXFREE TABLE
DROP TABLE TAXFREE;
DROP SEQUENCE PRODUCT_SEQ;

CREATE SEQUENCE PRODUCT_SEQ MAXVALUE 9999999999 NOCYCLE NOCACHE;
CREATE TABLE TAXFREE (
    PNUM    NUMBER(10)   PRIMARY KEY, -- 상품 번호(시퀀스)
    PNAME   VARCHAR2(50) NOT NULL,    -- 상품 이름
    PPRICE  NUMBER(10)   NOT NULL,    -- 상품 가격
    PIMAGE1 VARCHAR2(50),             -- 상품 메인 이미지
    PIMAGE2 VARCHAR2(50),             -- 상품 이미지2
    PIMAGE3 VARCHAR2(50),             -- 상품 이미지3
    PSTOCK  NUMBER(10)   NOT NULL,    -- 상품 재고
    PLOC    VARCHAR2(50) NOT NULL,    -- 상품의 현재 위치(도시)
    PCATEGORY VARCHAR2(50) NOT NULL   -- 상품 분류
);

-- DUMMY
-- FOOD DUMMY
-- 술
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'JW BLUE LABEL GHOST AND RARE GLENURY 1000ML', 399, 'FOOD4.jpg', 'FOOD4.jpg', 'FOOD4.jpg', 100, 'INCHEON', 'FOOD');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'TALISKER DARK STORM 1000ML', 103, 'FOOD2.jpg', 'FOOD3.jpg', 'FOOD2.jpg', 100, 'INCHEON', 'FOOD');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'MORTLACH SINGLE MALT SCOTCH WHISKY 750ML', 106, 'FOOD7.jpg', 'FOOD5.jpg', 'FOOD6.jpg', 100, 'LONDON', 'FOOD');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'THE SINGLETON OF GLENDULLAN 15 YEAR OLD', 102, 'FOOD11.jpg', 'FOOD10.jpg', 'FOOD12.jpg', 100, 'SCOTLAND', 'FOOD');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'ROYAL SALUTE UNION OF THE CROWNS BLENDED OF SCOTCH WHISKY', 399, 'FOOD13.jpg', 'FOOD14.jpg', 'FOOD15.jpg', 100, 'SCOTLAND', 'FOOD');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'BALLANTINE AGED 30 YEARS', 399, 'FOOD16.jpg', 'FOOD17.jpg', 'FOOD16.jpg', 100, 'SCOTLAND', 'FOOD'); 
-- 초콜릿
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'GODIVA CHOCOLATE DOMES (28PCS)', 26, 'FOOD1.jpg', 'FOOD1.jpg', 'FOOD1.jpg', 100, 'OSAKA', 'FOOD');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'GODIVA CHOCOLATE PEARLS TRIOPACK', 17, 'FOOD18.jpg', 'FOOD18.jpg', 'FOOD18.jpg', 100, 'ANKARA', 'FOOD');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'HAWAIIAN HOST TIKI-WHOLE HALVES 454G', 27, 'FOOD9.jpg', 'FOOD21.jpg', 'FOOD9.jpg', 100, 'VANCOUVER', 'FOOD');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'HAWAIIAN HOST CLASSIC COLLECTION 198G', 16, 'FOOD19.jpg', 'FOOD20.jpg', 'FOOD19.jpg', 100, 'ANKARA', 'FOOD');

-- ACCESSORY DUMMY
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'FENDI NEW QUARDRO', 1165, 'A1-1.jpg', 'A1-2.jpg', 'A1-3.jpg', 100, 'NEWYORK', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'FENDI NEW SELLERIA', 1530, 'A2-1.jpg', 'A2-2.jpg', 'A2-3.jpg', 100, 'LA', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'TAG HEUER CARRERA WAR201A', 2700, 'A3-1.jpg', 'A3-2.jpg', 'A3-3.jpg', 100, 'BOSTON', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'ORIS ARTELIER CALIBRE 111', 14260, 'A4-1.jpg', 'A4-2.jpg', 'A4-3.jpg', 100, 'MADRID', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'MONTBLANC SATR LEGACY CRONO DATE', 4700, 'A5-1.jpg', 'A5-2.jpg', 'A5-3.jpg', 100, 'PARIS', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'MONTBLANC TRADITION AUTOMATIC DATE', 1740, 'A6-1.jpg', 'A6-2.jpg', 'A6-3.jpg', 100, 'PARIS', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'TAG HEUER CARRERA WAR201A.BA0723', 2700, 'A11-1.jpg', 'A11-2.jpg', 'A11-3.jpg', 100, 'LA', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'EMPORIO ARMANI WH2', 285, 'A8-1.jpg', 'A8-2.jpg', 'A8-3.jpg', 100, 'SIDNEY', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'EMPORIO ARMANI WH', 292, 'A9-1.jpg', 'A9-2.jpg', 'A9-3.jpg', 100, 'HONGKONG', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'TISSOT SUPERSPORT', 510, 'A10-1.jpg', 'A10-2.jpg', 'A10-3.jpg', 100, 'CHICAGO', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'COACH ALLIE 19X22', 288, 'A7-1.jpg', 'A7-2.jpg', 'A7-3.jpg', 100, 'LA', 'ACCESSORY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'SEIKO SSE045J1', 2421, 'A12-1.jpg', 'A12-2.jpg', 'A12-3.jpg', 100, 'ROTTERDAM', 'ACCESSORY');

-- BEAUTY DUMMY
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL GABRIELLE ESSENCE 50ML', 119, 'CHANEL1.jpg', 'CHANEL1-2.webp', 'CHANEL1-3.webp', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL CHANCE EAU TENDRE EDP 150ML', 197, 'CHANEL2.jpg', 'CHANEL2-2.webp', 'CHANEL2-3.webp', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'ALLURE HOMME SPORT COLOGNE 100ML', 109, 'CHANEL3.jpg', 'CHANEL3-2.webp', 'CHANEL3-3.webp', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL BLEU DE CHANEL LOTION', 57, 'CHANEL4.jpg', 'CHANEL4-2.webp', 'CHANEL4-3', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL ALLURE H.AFTER SHAVE LOTION 100ML', 57, 'CHANEL5.jpg', 'CHANEL5-2.webp', 'CHANEL5-3.webp', 100, 'PARIS' ,'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL N°5 THE HAIR MIST', 49, 'CHANEL6.jpg', 'CHANEL6-2.webp', 'CHANEL6-3.webp', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL PARIS-RIVIERA EDT SPRAY 125ML', 144, 'CHANEL7.jpg', 'CHANEL7-2.webp', 'CHANEL7-3.webp', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL LE BLANC MAKE UP BASE', 53, 'CHANEL8.jpg', 'CHANEL8.jpg', 'CHANEL8.jpg', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL ULTRA LE TEINT CUSHION', 61, 'CHANEL9.jpg', 'CHANEL9-2.webp', 'CHANEL9-3.webp', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL PDRE UNI.LIBRE', 55, 'CHANEL10.jpg', 'CHANEL10-2.webp', 'CHANEL10-3.webp', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL ROUGE ALLURE VELVET', 35, 'CHANEL11.jpg', 'CHANEL11-2.webp', 'CHANEL18.jpg', 100, 'PARIS', 'BEAUTY');
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL ROUGE COCO BLOOM', 35, 'CHANEL12.jpg', 'CHANEL12-2.webp', 'CHANEL17.jpg', 100, 'PARIS', 'BEAUTY');    
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, 'CHANEL ROUGE ALLURE INK', 35, 'CHANEL13.jpg', 'CHANEL14.jpg', 'CHANEL13.jpg', 100, 'PARIS', 'BEAUTY');
COMMIT;
    
-- (2) CART TABLE
DROP TABLE CART;
DROP SEQUENCE CART_SEQ;

CREATE SEQUENCE CART_SEQ MAXVALUE 9999999999 NOCYCLE NOCACHE;
CREATE TABLE CART(
    CARTNUM NUMBER(10)   PRIMARY KEY,                  -- 장바구니번호(시퀀스)
    PNUM    NUMBER(10)   NOT NULL REFERENCES TAXFREE,  -- 상품 번호
    MID     VARCHAR2(50) NOT NULL REFERENCES CUSTOMER, -- 회원 아이디
    COST    NUMBER(10)   NOT NULL,                     -- 가격
    QTY     NUMBER(10)   NOT NULL                      -- 수량
);

-- (3) ORDERS TABLE 
DROP TABLE ORDERS;
DROP SEQUENCE ORDER_SEQ;

CREATE SEQUENCE ORDER_SEQ MAXVALUE 9999999999 NOCYCLE NOCACHE;
CREATE TABLE ORDERS (
    OR_NUM NUMBER(10)   PRIMARY KEY,                  -- 주문 번호(시퀀스)
    MID    VARCHAR2(50) NOT NULL REFERENCES CUSTOMER, -- 회원 아이디
    ORDATE DATE DEFAULT SYSDATE NOT NULL              -- 주문 날짜
);

-- (4) ORDER_DETAIL
DROP TABLE ORDER_DETAIL;
DROP SEQUENCE ORDERDETAIL_SEQ;

CREATE SEQUENCE ORDERDETAIL_SEQ MAXVALUE 9999999999 NOCYCLE NOCACHE;
CREATE TABLE ORDER_DETAIL(
    ORD_NUM    NUMBER(10) PRIMARY KEY,                   -- 주문 완료 번호
    OR_NUM     NUMBER(10) NOT NULL REFERENCES ORDERS,    -- 주문 번호  
    PNUM       NUMBER(10) NOT NULL REFERENCES TAXFREE,   -- 상품 번호
    COST       NUMBER(10) NOT NULL,                      -- 총 상품 가격
    QTY        NUMBER(10) NOT NULL                       -- 수량
);

COMMIT;


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-- SQL / 면세품 taxfree
-- 1. insertProduct 상품등록
INSERT INTO TAXFREE (PNUM, PNAME, PPRICE, PIMAGE1, PIMAGE2, PIMAGE3, PSTOCK, PLOC, PCATEGORY)
    VALUES(PRODUCT_SEQ.NEXTVAL, '초콜릿', 10, NULL, NULL, NULL, 32, 'OASAKA', 'FOOD');
-- 2. detailProduct 상품 상세보기
SELECT * FROM TAXFREE WHERE PNUM = 1;
-- 3. modifyProduct 상품수정
UPDATE TAXFREE SET PNAME = 'LIPSTICK',
                   PPRICE = 12,
                   PIMAGE1 = NULL,
                   PIMAGE2 = NULL,
                   PIMAGE3 = NULL,
                   PSTOCK = 160,
                   PLOC   = 'LONDON',
                   PCATEGORY = 'FOOD'
                WHERE PNUM = 4;
-- 4. deleteProduct 상품삭제
DELETE FROM TAXFREE WHERE PNUM = 1;
-- 4. countProduct 상품개수(페이징)
-- 4-1. 전체리스트
SELECT COUNT(*) FROM TAXFREE;
-- 4-2. 카테고리 별 상품 개수 가져오기
SELECT COUNT(*) FROM TAXFREE WHERE PCATEGORY = 'BEAUTY';
-- 5. listProduct 상품리스트 - paging
-- 5-1. 전체리스트
SELECT * FROM TAXFREE ORDER BY PNUM DESC; -- 서브쿼리
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM TAXFREE ORDER BY PNUM DESC)A) WHERE RN BETWEEN 1 AND 2;
-- 5-2. 카테고리 별로 리스트 출력하기 / BEAUTY / FOOD
SELECT * FROM TAXFREE WHERE PCATEGORY = 'BEAUTY' ORDER BY PNUM; -- 서브쿼리
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM TAXFREE WHERE PCATEGORY = 'BEAUTY' ORDER BY PNUM)A) WHERE RN BETWEEN 1 AND 2;


--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- SQL / 장바구니 CART
-- 1. insertCart 장바구니 추가
INSERT INTO CART (CARTNUM, PNUM, MID, COST, QTY)
    VALUES(CART_SEQ.NEXTVAL, 1, 'aaa', 1*(SELECT PPRICE FROM TAXFREE WHERE PNUM = 1), 1);
-- 2. deleteCartAll 장바구니 전체 삭제
DELETE FROM CART WHERE MID = 'aaa';
-- 3. deleteCart 장바구니 리스트 하나 삭제
DELETE FROM CART WHERE CARTNUM = 1;
-- 4. listCart 장바구니 리스트
SELECT * FROM CART C, TAXFREE T WHERE C.PNUM = T.PNUM AND MID = 'aaa' ORDER BY CARTNUM DESC;
-- 5. totCntCart 장바구니에 상품이 있는지 없는지 확인  
SELECT COUNT(*) FROM CART WHERE MID = 'aaa' AND PNUM = 1;
-- 6. updateCart 면세품상세보기 페이지에서 이미 담긴 상품을 수량을 수정하고 싶을때 
UPDATE CART SET QTY = 2 + (SELECT QTY FROM CART WHERE PNUM = 1 AND MID = 'aaa'),
                COST = (2 + (SELECT QTY FROM CART WHERE PNUM = 1 AND MID = 'aaa')) * (SELECT PPRICE FROM TAXFREE WHERE PNUM = 1)
            WHERE PNUM = 1 AND MID = 'aaa';
-- 7. updateInCart 장바구니 리스트에서 상품의 개수를 수정하고 싶은 경우
UPDATE CART SET QTY = 2,
                COST = 2 * (SELECT PPRICE FROM TAXFREE WHERE PNUM = (SELECT PNUM FROM CART WHERE CARTNUM = 30))
            WHERE CARTNUM = 30;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- SQL / 주문테이블 ORDERS & ORDER_DETAIL
-- 1. insertOrder 장바구니에 담긴 물건들 하나의 주문번호로 생성
INSERT INTO ORDERS VALUES (ORDER_SEQ.NEXTVAL, 'aaa', SYSDATE);
-- 2. insertOrderDetail 하나의 주문번호로 만든 주문 내역들 출력하기
INSERT INTO ORDER_DETAIL 
    SELECT ORDERDETAIL_SEQ.NEXTVAL, (SELECT MAX(OR_NUM) FROM ORDERS), PNUM, COST, QTY FROM CART WHERE MID= 'aaa';
-- 3. updateStock 주문완료 후 재고 업데이트
UPDATE TAXFREE SET PSTOCK = PSTOCK - (SELECT QTY FROM CART WHERE PNUM = 1) WHERE PNUM = 1;
-- 4. cartDelete 주문 완료 후 장바구니 내역 삭제
DELETE CART WHERE MID = 'aaa';
-- 6. myOrderDetail 주문정보 출력
SELECT OD.OR_NUM, ORDATE, PIMAGE1, PNAME, OD.QTY, PPRICE, OD.COST 
    FROM ORDER_DETAIL OD, ORDERS O, TAXFREE T  
        WHERE OD.OR_NUM = O.OR_NUM AND T.PNUM = OD.PNUM AND O.MID = 'aaa'
        	ORDER BY ORDATE DESC, OR_NUM ASC;

--------------------------------------------------------------------------------
COMMIT;


